import test from "node:test";
import assert from "node:assert/strict";
import {predict,capacity,emptyPlan,defaultSettings,planSchema,settingsSchema,operationalHours,resolveDependencies,accuracy} from "../src/lib/delay.js";
function sample(){return {now:"2026-09-14T06:00:00Z",vehicle:{id:"v",stage:"IN_LAVORAZIONE",dataIngresso:"2026-09-10T08:00:00Z",stageEnteredAt:"2026-09-14T06:00:00Z",dataPrevistaConsegna:"2026-09-17T12:00:00Z"},settings:{...defaultSettings(),calendarConfirmed:true,technicians:[{userId:"t",department:"carrozzeria",hoursPerDay:8,unavailableDates:[]}]},hours:emptyPlan().hours.map((h,i)=>({...h,planned:i===0?8:0,completed:0})),dependencies:[],depsReviewed:true,queue:{},history:[],appointments:[]};}
test("ore, data promessa invariata, indice spiegato",()=>{const x=sample(),before=JSON.stringify(x);const r=predict(x);assert.equal(r.estimatedDate,"2026-09-14");assert.equal(r.remainingHours,8);assert.equal(r.band,"green");assert.equal(JSON.stringify(x),before);assert.ok(r.factors.some(f=>f.code==="schedule"));});
test("più ore, coda e carico aumentano rischio",()=>{const x=sample(),base=predict(x);x.queue.carrozzeria=40;const r=predict(x);assert.ok(r.risk>base.risk);assert.equal(r.band,"red");assert.ok(r.factors.some(f=>f.code==="pressure"));});
test("festività e weekend esclusi",()=>{const x=sample();x.now="2026-09-18T06:00:00Z";x.settings.closures=[{from:"2026-09-18",to:"2026-09-18",label:"Chiusura"}];assert.equal(predict(x).estimatedDate,"2026-09-21");});
test("assenza tecnico assegnato non sostituita silenziosamente",()=>{const x=sample();x.vehicle.tecnicoId="t";x.settings.technicians[0].unavailableDates=["2026-09-14"];x.settings.technicians.push({userId:"other",department:"carrozzeria",hoursPerDay:8,unavailableDates:[]});assert.equal(predict(x).estimatedDate,"2026-09-15");});
test("ETA mancante o scaduta non produce una data inventata",()=>{const x=sample();x.dependencies=[{kind:"part",description:"Paraurti",done:false,eta:null}];let r=predict(x);assert.equal(r.estimatedDate,null);assert.equal(r.risk,null);assert.ok(r.factors.some(f=>f.text.includes("Paraurti")));x.dependencies[0].eta="2026-09-13";assert.equal(predict(x).estimatedDate,null);x.dependencies[0].eta="2026-09-18";assert.equal(predict(x).estimatedDate,"2026-09-18");});
test("ordine collegato legge quantità ricevute ed ETA reali",()=>{const p=emptyPlan();p.dependencies=[{id:"d",kind:"part",description:"X",orderItemId:"i",done:true,eta:"2026-09-14"}];const d=resolveDependencies(p,[{id:"i",descrizione:"Paraurti",quantitaOrdinata:2,quantitaRicevuta:1,supplierOrder:{dataConsegnaPrevista:"2026-09-17T12:00:00Z"}}])[0];assert.equal(d.done,false);assert.equal(d.eta,"2026-09-17");assert.equal(resolveDependencies(p,[])[0].done,false);});
test("ore mancanti, nessuna promessa e calendario non confermato",()=>{const x=sample();x.hours=emptyPlan().hours;assert.equal(predict(x).risk,null);x.hours=sample().hours;x.settings.calendarConfirmed=false;assert.equal(predict(x).estimatedDate,null);x.settings.calendarConfirmed=true;x.vehicle.dataPrevistaConsegna=null;assert.equal(predict(x).risk,null);});
test("ritardo già osservato distinto dalla previsione",()=>{const x=sample();x.vehicle.dataPrevistaConsegna="2026-09-13T12:00Z";x.hours=emptyPlan().hours;const r=predict(x);assert.equal(r.risk,100);assert.ok(r.factors.some(f=>f.code==="overdue"));});
test("appuntamenti sovrapposti contati una volta, ore pratica non duplicate",()=>{const x=sample();x.appointments=[{tecnicoId:"t",vehicleId:null,inizio:"2026-09-14T07:00Z",fine:"2026-09-14T09:00Z"},{tecnicoId:"t",vehicleId:null,inizio:"2026-09-14T08:00Z",fine:"2026-09-14T10:00Z"}];assert.equal(capacity("2026-09-14","carrozzeria",x),5);x.appointments[0].vehicleId="v";x.appointments[1].vehicleId="v";x.accountedVehicleIds=["v"];assert.equal(capacity("2026-09-14","carrozzeria",x),8);});
test("storico reale usato solo con almeno cinque vetture",()=>{const x=sample();x.hours=emptyPlan().hours;x.history=[2,3,4,5];assert.equal(predict(x).estimatedDate,null);x.history.push(6);assert.equal(predict(x).estimatedDate,"2026-09-18");});
test("Profit Tracker utilizza solo ore e segnala completamento sconosciuto",()=>{const p=emptyPlan();p.source="profit";let h=operationalHours(p,null);assert.equal(h.rows[0].planned,null);h=operationalHours(p,{plannedComplete:true,actualComplete:false,costs:[{category:"carrozziere",phase:"planned",quantity:7.5,unitCents:99999}]});assert.equal(h.rows[0].planned,7.5);assert.equal(h.rows[0].completed,null);assert.ok(!JSON.stringify(h).includes("99999"));});
test("validazione date, ore e tecnici duplicati",()=>{assert.equal(planSchema.safeParse(emptyPlan()).success,true);const x=sample();assert.equal(settingsSchema.safeParse(x.settings).success,true);x.settings.closures=[{from:"2026-02-30",to:"2026-03-02",label:"X"}];assert.equal(settingsSchema.safeParse(x.settings).success,false);const p=emptyPlan();p.hours[0].planned=-1;assert.equal(planSchema.safeParse(p).success,false);});
test("accuratezza: prima previsione prospettica, non ultima o post-consegna",()=>{const f={vehicleId:"v",risk:70,createdAt:"2026-09-10T08:00Z",promisedAt:"2026-09-14T12:00Z",estimatedDate:"2026-09-15",actualDeliveredAt:"2026-09-16T12:00Z"};const m=accuracy([f,{...f,risk:10,createdAt:"2026-09-11T08:00Z"},{...f,vehicleId:"late",createdAt:"2026-09-17T08:00Z"}]);assert.equal(m.sampleSize,1);assert.equal(m.classificationAccuracy,100);assert.equal(m.meanAbsoluteDaysError,1);assert.equal(m.bins[2].late,1);});
