import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import jwt from 'jsonwebtoken';
import {prisma} from '../src/lib/prisma.js';
import {delayRouter} from '../src/routes/delay.js';
import {emptyPlan,defaultSettings} from '../src/lib/delay.js';
prisma.trackedPart.findMany=async()=>[];
process.env.JWT_SECRET='isolated-delay-tests';
let role='ADMIN',plan=null,config=null,forecasts=[],decisions=[];
const v={id:'v',marca:'TEST',modello:'TEST',targa:'TEST',stage:'IN_LAVORAZIONE',dataIngresso:new Date(),dataPrevistaConsegna:new Date(Date.now()+14*86400000),dataConsegnaEffettiva:null,tecnicoId:'u',stageHistory:[]};
const originalPromise=v.dataPrevistaConsegna.toISOString();
prisma.user.findFirst=async({where})=>where.tenantId==='a'?{ruolo:role}:null;
prisma.user.findMany=async()=>[{id:'u',nome:'Test',cognome:'Test',ruolo:role}];
prisma.user.count=async({where})=>where.id.in.filter(id=>id==='u').length;
prisma.vehicle.findMany=async({where})=>{assert.equal(where.tenantId,'a');return[v];};
prisma.vehicle.findFirst=async({where})=>where.tenantId==='a'&&where.id==='v'&&(!where.tecnicoId||where.tecnicoId==='u')?v:null;
prisma.delaySettings.findUnique=async()=>config;
prisma.delaySettings.create=async({data})=>{if(config)throw Object.assign(new Error(),{code:'P2002'});return config={...data,version:1};};
prisma.delaySettings.updateMany=async({where,data})=>{if(config?.version!==where.version)return{count:0};config={...config,data:data.data,version:config.version+1};return{count:1};};
prisma.delayPlan.findMany=async()=>plan?[plan]:[];
prisma.delayPlan.create=async({data})=>{if(plan)throw Object.assign(new Error(),{code:'P2002'});return plan={...data,version:1};};
prisma.delayPlan.updateMany=async({where,data})=>{assert.equal(where.tenantId,'a');if(plan?.version!==where.version)return{count:0};plan={...plan,data:data.data,version:plan.version+1};return{count:1};};
prisma.profitRecord.findMany=async()=>[];
prisma.appointment.findMany=async()=>[];
prisma.supplierOrderItem.findMany=async()=>[];
prisma.supplierOrderItem.count=async({where})=>{assert.equal(where.supplierOrder.tenantId,'a');return 0;};
prisma.stageHistory.findMany=async()=>[];
prisma.delayForecast.upsert=async({create})=>{const exists=forecasts.find(f=>f.fingerprint===create.fingerprint);if(exists)return exists;const f={...create,id:'f'+forecasts.length,createdAt:new Date(),actualDeliveredAt:null};forecasts.push(f);return f;};
prisma.delayForecast.findMany=async({where})=>where.actualDeliveredAt?[]:forecasts;
prisma.delayForecast.findFirst=async({where,orderBy})=>{assert.equal(where.tenantId,'a');return where.id?forecasts.find(f=>f.id===where.id&&f.vehicleId===where.vehicleId)??null:orderBy.createdAt==='asc'?forecasts[0]??null:forecasts.at(-1)??null;};
prisma.delayDecision.findMany=async()=>decisions;
prisma.delayDecision.create=async({data})=>{const d={...data,id:'d'+decisions.length,createdAt:new Date()};decisions.push(d);return d;};
const app=express();app.use(express.json());app.use('/api/delay',delayRouter);app.use((e,req,res,next)=>res.status(500).json({error:e.message}));
const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const call=(path,method='GET',body,token=true)=>fetch(`http://127.0.0.1:${server.address().port}/api/delay`+path,{method,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+jwt.sign({sub:'u',tenantId:'a',role:'ADMIN'},process.env.JWT_SECRET)}:{})},body:body?JSON.stringify(body):undefined});
test('API ritardi: permessi, tenant, versioni, storico e nessuna modifica promessa',async()=>{try{
 assert.equal((await call('/dashboard','GET',null,false)).status,401);
 assert.equal((await call('/vehicles/foreign')).status,404);
 const first=await(await call('/vehicles/v')).json();assert.equal(first.forecast.risk,null);assert.equal(first.initial.id,first.forecast.id);assert.equal(first.forecast.input,undefined);
 const settings={...defaultSettings(),calendarConfirmed:true,technicians:[{userId:'u',department:'carrozzeria',hoursPerDay:8,unavailableDates:[]}]};
 role='TECNICO';assert.equal((await call('/settings')).status,403);assert.equal((await call('/vehicles/v','PUT',{version:0,data:emptyPlan()})).status,403);const tech=await(await call('/vehicles/v')).json();assert.equal(tech.canEdit,false);assert.deepEqual(tech.orderItems,[]);
 role='ADMIN';assert.equal((await call('/settings','PUT',{version:0,data:settings})).status,200);assert.equal((await call('/settings','PUT',{version:0,data:settings})).status,409);
 const data=emptyPlan();data.hours=data.hours.map((h,i)=>({...h,planned:i===0?8:0,completed:0}));data.dependenciesReviewed=true;
 assert.equal((await call('/vehicles/v','PUT',{version:0,data})).status,200);assert.equal((await call('/vehicles/v','PUT',{version:0,data})).status,409);
 const saved=await(await call('/vehicles/v')).json();assert.equal(saved.initial.id,first.initial.id);assert.ok(saved.forecast.risk!==null);
 const bad={...data,dependencies:[{id:'d',kind:'part',description:'Foreign',orderItemId:'foreign',eta:null,done:false}]};assert.equal((await call('/vehicles/v','PUT',{version:1,data:bad})).status,400);
 const decision={forecastId:saved.forecast.id,action:'REVISE',proposedDate:'2026-10-01',note:'Prova'};
 assert.equal((await call('/vehicles/v/decisions','POST',{...decision,forecastId:'foreign'})).status,404);
 assert.equal((await call('/vehicles/v/decisions','POST',decision)).status,201);
 assert.equal((await call('/vehicles/v/decisions','POST',{...decision,action:'KEEP',proposedDate:null})).status,201);
 assert.equal((await call('/vehicles/v/decisions','POST',{...decision,action:'DRAFT',proposedDate:null,note:'Bozza non inviata'})).status,201);
 assert.equal(v.dataPrevistaConsegna.toISOString(),originalPromise);
 assert.equal(decisions.length,3);assert.equal(decisions[2].action,'DRAFT');
 const dashboard=await(await call('/dashboard')).json();assert.equal(dashboard.rows.length,1);assert.equal(dashboard.accuracy.sampleSize,0);
 }finally{await new Promise(r=>server.close(r));await prisma.$disconnect();}});
