import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import jwt from 'jsonwebtoken';
import {prisma} from '../src/lib/prisma.js';
import {partsTrackingRouter} from '../src/routes/partsTracking.js';
import {emptyTrackedPart} from '../src/lib/parts-tracking.js';
process.env.JWT_SECRET='isolated-parts-test';
let role='ADMIN';
prisma.user.findFirst=async()=>({ruolo:role});
prisma.vehicle.findFirst=async({where})=>where.id==='v'&&where.tenantId==='a'?{id:'v'}:null;
prisma.trackedPart.findMany=async({where})=>{assert.equal(where.tenantId,'a');return where.orderItemId?[]:[{id:'p',data:{...emptyTrackedPart(),code:'TEST',description:'Test',actualUnitCents:12345},status:'ARRIVATO',events:[],documents:[]}];};
prisma.trackedPart.findFirst=async({where})=>{assert.equal(where.tenantId,'a');assert.equal(where.vehicle.tenantId,'a');return where.id==='p'?{id:'p',vehicleId:'v',status:'DA_ORDINARE'}:null;};
prisma.vehiclePartBlock.findMany=async()=>[];prisma.profitRecord.findFirst=async()=>null;prisma.supplierOrderItem.findMany=async()=>[];prisma.part.findMany=async()=>[];
prisma.trackedPartDocument.findFirst=async({where})=>{assert.equal(where.tenantId,'a');assert.equal(where.part.vehicle.tenantId,'a');return null;};
const app=express();app.use(express.json());app.use('/parts',partsTrackingRouter);app.use((e,req,res,next)=>res.status(500).json({error:e.message}));
const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const call=(path,method='GET',body,auth=true)=>fetch(`http://127.0.0.1:${server.address().port}/parts${path}`,{method,headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+jwt.sign({sub:'u',tenantId:'a',role:'ADMIN'},process.env.JWT_SECRET)}:{})},body:body?JSON.stringify(body):undefined});
test('API Parts: tenant, ruolo corrente, prezzi, documenti e transizioni tecnico',async()=>{try{
 assert.equal((await call('/vehicles/v','GET',null,false)).status,401);
 assert.equal((await call('/vehicles/foreign')).status,404);
 assert.equal((await(await call('/vehicles/v')).json()).parts[0].data.actualUnitCents,12345);
 role='TECNICO';const r=await(await call('/vehicles/v')).json();assert.equal(r.parts[0].data.actualUnitCents,undefined);assert.equal(r.canEdit,false);assert.deepEqual(r.orders,[]);
 assert.equal((await call('/vehicles/v','POST',{})).status,403);
 assert.equal((await call('/documents/x')).status,403);
 assert.equal((await call('/parts/p/status','POST',{version:1,status:'MONTATO',reason:'No'})).status,403);
 role='ACCETTATORE';assert.equal((await call('/documents/x')).status,403);
 role='ADMIN';assert.equal((await call('/documents/foreign')).status,404);
 }finally{await new Promise(r=>server.close(r));await prisma.$disconnect();}});
