import 'dotenv/config';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {prisma} from '../src/lib/prisma.js';
import {saveTrackedPart} from '../src/lib/parts-tracking-service.js';
import {emptyTrackedPart,partsProfitData} from '../src/lib/parts-tracking.js';
import {calculate} from '../src/lib/profit.js';
const rollback=new Error('ROLLBACK_PARTS_TEST'),original=prisma.$transaction.bind(prisma);
try{await original(async tx=>{
 prisma.$transaction=async fn=>fn(tx);
 const tenant=await tx.tenant.create({data:{ragioneSociale:'Verifica transitoria Parts Tracking'}}),tenantId=tenant.id;
 const client=await tx.client.create({data:{tenantId,nome:'Test',cognome:'Transitorio'}});
 const v=await tx.vehicle.create({data:{tenantId,clientId:client.id,marca:'TEST',modello:'TEST',targa:'TEST-PARTS'}});
 const base={tenantId,vehicleId:v.id,requestKey:randomUUID(),version:0,actorId:'test',financial:true,reason:'',status:'DA_ORDINARE',data:{...emptyTrackedPart(),code:'TEST',description:'Test',blocking:true,plannedUnitCents:10000,actualUnitCents:12000,quantity:2}};
 const p=await saveTrackedPart(structuredClone(base));assert.equal((await saveTrackedPart(structuredClone(base))).id,p.id);
 await assert.rejects(()=>saveTrackedPart({...structuredClone(base),id:p.id,version:0}),e=>e.status===409);
 await assert.rejects(()=>saveTrackedPart({...structuredClone(base),id:p.id,version:1,status:'MONTATO'}),e=>e.status===400);
 await assert.rejects(()=>saveTrackedPart({...structuredClone(base),id:p.id,version:1,financial:false}),e=>e.status===403);
 const p2=await saveTrackedPart({...structuredClone(base),requestKey:randomUUID()});
 assert.equal(await tx.vehiclePartBlock.count({where:{vehicleId:v.id,endedAt:null}}),1);
 await saveTrackedPart({...structuredClone(base),id:p.id,version:1,status:'CONTROLLATO',reason:'Verifica controllo'});
 assert.equal(await tx.vehiclePartBlock.count({where:{vehicleId:v.id,endedAt:null}}),1);
 await saveTrackedPart({...structuredClone(base),id:p2.id,version:1,status:'CONTROLLATO',reason:'Verifica controllo'});
 assert.equal(await tx.vehiclePartBlock.count({where:{vehicleId:v.id,endedAt:null}}),0);
 const order=await tx.supplierOrder.create({data:{tenantId,fornitore:'Test fornitore',items:{create:{descrizione:'Ordinato',quantitaOrdinata:2,quantitaRicevuta:2}}},include:{items:true}});
 const catalog=await tx.part.create({data:{tenantId,codice:'TESTCAT',descrizione:'Test catalogo',prezzoAcquisto:1,prezzoVendita:2}});
 const linked=await saveTrackedPart({...structuredClone(base),requestKey:randomUUID(),catalogPartId:catalog.id,orderItemId:order.items[0].id,data:{...base.data,blocking:false,plannedUnitCents:null,actualUnitCents:null}});
 assert.equal(linked.status,'ARRIVATO');assert.equal(linked.data.arrivedDate,null);
 await tx.part.delete({where:{id:catalog.id}});await tx.supplierOrderItem.delete({where:{id:order.items[0].id}});
 const retained=await tx.trackedPart.findUnique({where:{id:linked.id}});assert.equal(retained.catalogPartId,null);assert.equal(retained.orderItemId,null);assert.equal(retained.data.code,'TEST');
 const ledger=await tx.profitRecord.findUnique({where:{vehicleId:v.id}}),parts=await tx.trackedPart.findMany({where:{vehicleId:v.id}});
 assert.equal(ledger.data.costs.length,0);assert.equal(calculate(partsProfitData(ledger.data,parts).data).actual,48000);
 await tx.trackedPartDocument.create({data:{tenantId,partId:p.id,name:'test.pdf',mime:'application/pdf',content:Buffer.from('%PDF-1.7'),size:8}});
 await saveTrackedPart({...structuredClone(base),id:p.id,version:2,status:'DA_ORDINARE',reason:'Riapertura test'});
 assert.equal(await tx.vehiclePartBlock.count({where:{vehicleId:v.id,endedAt:null}}),1);
 await tx.vehicle.update({where:{id:v.id},data:{stage:'CONSEGNATA',dataConsegnaEffettiva:new Date()}});
 assert.equal(await tx.vehiclePartBlock.count({where:{vehicleId:v.id,endedAt:null}}),0);
 assert.equal(await tx.trackedPartEvent.count({where:{partId:p.id}}),3);
 throw rollback;
},{timeout:40000});}catch(e){if(e!==rollback)throw e;console.log('Database: salvataggio, idempotenza, conflitti, permessi, costi, documenti, fermi multipli e consegna verificati. Dati di prova annullati integralmente.');}finally{prisma.$transaction=original;await prisma.$disconnect();}
