import test from 'node:test';
import assert from 'node:assert/strict';
import 'dotenv/config';
import {PHOTO_CATEGORIES,photoMeta,phaseForCategory,photoStoragePath,dossierPhotos,timelineEditSchema,suggestionSchema} from '../src/lib/photo-timeline.js';
test('dieci categorie e compatibilità prima/durante/dopo',()=>{assert.equal(Object.keys(PHOTO_CATEGORIES).length,10);assert.equal(phaseForCategory('DANNI_INIZIALI'),'PRIMA');assert.equal(phaseForCategory('DANNI_NASCOSTI'),'DURANTE');assert.equal(phaseForCategory('CONSEGNA'),'DOPO');assert.equal(phaseForCategory(null,'PRIMA'),'PRIMA');assert.equal(photoMeta({}).authorName,null);});
test('rettifiche manuali non permettono autore o AI inventati',()=>{const d={category:'DANNI_NASCOSTI',capturedAt:null,notes:'Danno',internalNotes:'Riservato',workDescription:'Smontaggio',markers:[{x:.1,y:.2,w:.2,h:.3,label:'Danno'}]};assert.ok(timelineEditSchema.safeParse(d).success);assert.equal(timelineEditSchema.safeParse({...d,authorName:'Falso'}).success,false);assert.equal(timelineEditSchema.safeParse({...d,markers:[{x:.9,y:0,w:.2,h:.3,label:''}]}).success,false);assert.equal(suggestionSchema.safeParse({category:'ALTRO',confidence:100,reason:''}).success,false);});
test('archivio foto limitato a host, tenant e pratica',()=>{const p={vehicleId:'v',url:'https://store.example/storage/v1/object/public/vehicle-photos/t/v/test.jpg'};assert.equal(photoStoragePath(p,'t','https://store.example','vehicle-photos'),'t/v/test.jpg');for(const url of ['http://127.0.0.1/admin','https://evil.example/test','https://store.example/storage/v1/object/public/vehicle-photos/other/v/a.jpg','https://store.example/storage/v1/object/public/vehicle-photos/t/v/%2e%2e%2fa.jpg'])assert.throws(()=>photoStoragePath({...p,url},'t','https://store.example','vehicle-photos'));});
test('dossier seleziona solo foto esistenti e ordina categorie/date senza attribuire dati storici',()=>{const photos=[{id:'old',createdAt:'2026-09-01',timeline:{}},{id:'end',createdAt:'2026-09-04',timeline:{category:'CONSEGNA'}},{id:'start',createdAt:'2026-09-01',timeline:{category:'DANNI_INIZIALI'}}];assert.deepEqual(dossierPhotos(photos).map(p=>p.id),['start','end','old']);assert.throws(()=>dossierPhotos(photos,['foreign']));assert.throws(()=>dossierPhotos(photos,['old','old']));assert.equal(photoMeta(photos[0]).capturedAt,null);});

test('portale cliente conserva solo i campi fotografici pubblici storici',async()=>{const {publicPhoto}=await import('../src/lib/photo-timeline.js');const p=publicPhoto({id:'p',url:'image.jpg',timeline:{internalNotes:'SEGRETO',authorId:'u',originalUrl:'raw.jpg'},timelineVersion:4});assert.equal(p.timeline,undefined);assert.equal(JSON.stringify(p).includes('SEGRETO'),false);assert.equal(p.url,'image.jpg');});
